---
users:
  - name: bob
    privilege: 5
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      31313638356537313535353337336262363465633661613962633030636234306438366231663866
      3832303763343061613134656132613634633038313935640a333532623331663964656433396264
      65613262303339363839663664656165353534613332396564633734663865376237393865303964
      3533366165643332340a383664613033393661343262656638633763613566653730376361366365
      6462

  - name: alice 
    privilege: 15
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62633239396666623365663463653561613034333534306466343439636530343366353837326136
      6263616361633966616163326434323238646233313134360a626362383561306132643334313961
      34613535346333633931336236303335666661336162656361363038346336373637663937636638
      3166333739363061390a333463636637386639373931333438373035303736386562323133633038
      37663334653933613465336362383437386633636132393130663461323236306632

  - name: regis
    privilege: 1
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34366634313435366531393763666234363965643565356232343939363838653731313165306239
      6366636230636461663363623131386234306361353239630a363835643037356436303432393439
      33653331366664316462336639333362303838613635386331613766396537376534663430613563
      3335356662656231360a313065356238346464336438346561616637336236663038363064623466
      3061

Loopback100: 10.10.100.1 255.255.255.255

GigabitEthernet2: 10.10.10.32 255.255.255.0

GigabitEthernet3: 10.10.10.33 255.255.255.0
