# Example host_vars for Catalyst8k

---
users:
  - name: bob
    privilege: 5
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      <encrypted-placeholder>

  - name: alice 
    privilege: 15
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      <encrypted-placeholder>

  - name: regis
    privilege: 1
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      <encrypted-placeholder>

# Don't touch GigabitEthernet1 with IOS XE on Cat8kv sandbox

Loopback100: 10.10.100.1 255.255.255.255

GigabitEthernet2: 10.10.10.32 255.255.255.0

GigabitEthernet3: 10.10.10.33 255.255.255.0
